import type { Metadata } from "next";
import "./globals.scss";
import Navbar from "../components/Navbar";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Toaster />
      </body>
    </html>
  );
}

// TODO: firebase modular upgrade (https://firebase.google.com/docs/web/modular-upgrade?hl=ru)
